#!/usr/bin/env bash
# analyze-coverage.sh
# Reads lcov or JSON coverage reports and outputs actionable improvement suggestions.
# Usage: ./analyze-coverage.sh [coverage-file] [--format lcov|json] [--threshold 80]
#
# Supports:
#   - lcov.info (generated by v8, istanbul, nyc)
#   - coverage-summary.json (generated by vitest --reporter=json-summary)

set -euo pipefail

COVERAGE_FILE="${1:-coverage/coverage-summary.json}"
FORMAT="${2:-auto}"
THRESHOLD="${3:-80}"

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[FAIL]${NC} $1"; }
log_success() { echo -e "${GREEN}[ OK ]${NC} $1"; }

# Auto-detect format
if [[ "$FORMAT" == "auto" ]]; then
  if [[ "$COVERAGE_FILE" == *.json ]]; then
    FORMAT="json"
  elif [[ "$COVERAGE_FILE" == *.info ]]; then
    FORMAT="lcov"
  else
    echo "Cannot auto-detect format for: $COVERAGE_FILE"
    echo "Pass --format lcov or --format json"
    exit 1
  fi
fi

if [[ ! -f "$COVERAGE_FILE" ]]; then
  log_error "Coverage file not found: $COVERAGE_FILE"
  echo ""
  echo "Generate it with one of:"
  echo "  npx vitest run --coverage --coverage.reporter=json-summary"
  echo "  npx jest --coverage --coverageReporters=json-summary"
  echo "  npx c8 --reporter=lcov vitest run"
  exit 1
fi

echo ""
echo "======================================"
echo " Coverage Analysis Report"
echo "======================================"
echo " File   : $COVERAGE_FILE"
echo " Format : $FORMAT"
echo " Target : ${THRESHOLD}%"
echo "======================================"
echo ""

# Parse JSON coverage summary (vitest/jest --reporter=json-summary)
if [[ "$FORMAT" == "json" ]]; then

  if ! command -v jq &>/dev/null; then
    log_error "jq is required for JSON parsing. Install: brew install jq"
    exit 1
  fi

  # Extract totals
  TOTAL_STATEMENTS=$(jq -r '.total.statements.pct // 0' "$COVERAGE_FILE")
  TOTAL_BRANCHES=$(jq -r '.total.branches.pct // 0' "$COVERAGE_FILE")
  TOTAL_FUNCTIONS=$(jq -r '.total.functions.pct // 0' "$COVERAGE_FILE")
  TOTAL_LINES=$(jq -r '.total.lines.pct // 0' "$COVERAGE_FILE")

  echo "=== TOTALS ==="
  for metric in "statements:$TOTAL_STATEMENTS" "branches:$TOTAL_BRANCHES" "functions:$TOTAL_FUNCTIONS" "lines:$TOTAL_LINES"; do
    label="${metric%%:*}"
    value="${metric##*:}"
    int_value="${value%.*}"
    if (( int_value >= THRESHOLD )); then
      log_success "$label: ${value}%"
    elif (( int_value >= THRESHOLD - 10 )); then
      log_warn "$label: ${value}% (below ${THRESHOLD}% target by $((THRESHOLD - int_value))%)"
    else
      log_error "$label: ${value}% (significantly below ${THRESHOLD}% target)"
    fi
  done

  echo ""
  echo "=== FILES BELOW THRESHOLD ==="
  echo ""

  # Find files below threshold — print file path, metric, and value
  BELOW_COUNT=0
  while IFS= read -r file_path; do
    if [[ "$file_path" == "total" ]]; then continue; fi

    stmt=$(jq -r --arg f "$file_path" '.[$f].statements.pct // 0' "$COVERAGE_FILE")
    branch=$(jq -r --arg f "$file_path" '.[$f].branches.pct // 0' "$COVERAGE_FILE")
    func=$(jq -r --arg f "$file_path" '.[$f].functions.pct // 0' "$COVERAGE_FILE")
    lines=$(jq -r --arg f "$file_path" '.[$f].lines.pct // 0' "$COVERAGE_FILE")

    stmt_int="${stmt%.*}"
    branch_int="${branch%.*}"
    func_int="${func%.*}"
    lines_int="${lines%.*}"

    issues=()
    (( stmt_int < THRESHOLD ))   && issues+=("statements=${stmt}%")
    (( branch_int < THRESHOLD )) && issues+=("branches=${branch}%")
    (( func_int < THRESHOLD ))   && issues+=("functions=${func}%")
    (( lines_int < THRESHOLD ))  && issues+=("lines=${lines}%")

    if [[ ${#issues[@]} -gt 0 ]]; then
      echo "  $file_path"
      for issue in "${issues[@]}"; do
        echo "    -> $issue"
      done
      echo ""
      (( BELOW_COUNT++ )) || true
    fi

  done < <(jq -r 'keys[]' "$COVERAGE_FILE")

  if [[ $BELOW_COUNT -eq 0 ]]; then
    log_success "All files meet the ${THRESHOLD}% threshold."
  else
    log_warn "$BELOW_COUNT file(s) are below the ${THRESHOLD}% threshold."
  fi

fi

# Parse LCOV format
if [[ "$FORMAT" == "lcov" ]]; then

  echo "=== LCOV SUMMARY ==="
  echo ""

  # Count totals from lcov
  TOTAL_FOUND_LINES=0
  TOTAL_HIT_LINES=0
  TOTAL_FOUND_FUNCS=0
  TOTAL_HIT_FUNCS=0
  TOTAL_FOUND_BRANCHES=0
  TOTAL_HIT_BRANCHES=0
  BELOW_FILES=()
  CURRENT_FILE=""

  while IFS= read -r line; do
    case "$line" in
      SF:*)
        CURRENT_FILE="${line#SF:}"
        FILE_LINES_FOUND=0; FILE_LINES_HIT=0
        FILE_FUNCS_FOUND=0; FILE_FUNCS_HIT=0
        FILE_BRANCHES_FOUND=0; FILE_BRANCHES_HIT=0
        ;;
      LF:*)  FILE_LINES_FOUND="${line#LF:}";      TOTAL_FOUND_LINES=$((TOTAL_FOUND_LINES + FILE_LINES_FOUND)) ;;
      LH:*)  FILE_LINES_HIT="${line#LH:}";         TOTAL_HIT_LINES=$((TOTAL_HIT_LINES + FILE_LINES_HIT)) ;;
      FNF:*) FILE_FUNCS_FOUND="${line#FNF:}";      TOTAL_FOUND_FUNCS=$((TOTAL_FOUND_FUNCS + FILE_FUNCS_FOUND)) ;;
      FNH:*) FILE_FUNCS_HIT="${line#FNH:}";        TOTAL_HIT_FUNCS=$((TOTAL_HIT_FUNCS + FILE_FUNCS_HIT)) ;;
      BRF:*) FILE_BRANCHES_FOUND="${line#BRF:}";   TOTAL_FOUND_BRANCHES=$((TOTAL_FOUND_BRANCHES + FILE_BRANCHES_FOUND)) ;;
      BRH:*) FILE_BRANCHES_HIT="${line#BRH:}";     TOTAL_HIT_BRANCHES=$((TOTAL_HIT_BRANCHES + FILE_BRANCHES_HIT)) ;;
      end_of_record)
        # Check per-file coverage
        if [[ $FILE_LINES_FOUND -gt 0 ]]; then
          pct=$(( (FILE_LINES_HIT * 100) / FILE_LINES_FOUND ))
          if (( pct < THRESHOLD )); then
            BELOW_FILES+=("$CURRENT_FILE (lines: ${pct}%)")
          fi
        fi
        ;;
    esac
  done < "$COVERAGE_FILE"

  # Compute and display totals
  LINE_PCT=$(( TOTAL_FOUND_LINES > 0 ? (TOTAL_HIT_LINES * 100) / TOTAL_FOUND_LINES : 0 ))
  FUNC_PCT=$(( TOTAL_FOUND_FUNCS > 0 ? (TOTAL_HIT_FUNCS * 100) / TOTAL_FOUND_FUNCS : 0 ))
  BRANCH_PCT=$(( TOTAL_FOUND_BRANCHES > 0 ? (TOTAL_HIT_BRANCHES * 100) / TOTAL_FOUND_BRANCHES : 0 ))

  for metric in "lines:$LINE_PCT" "functions:$FUNC_PCT" "branches:$BRANCH_PCT"; do
    label="${metric%%:*}"; value="${metric##*:}"
    if (( value >= THRESHOLD )); then
      log_success "$label: ${value}%"
    else
      log_error "$label: ${value}% (target: ${THRESHOLD}%)"
    fi
  done

  echo ""
  echo "=== FILES BELOW THRESHOLD ==="
  echo ""
  if [[ ${#BELOW_FILES[@]} -eq 0 ]]; then
    log_success "All files meet the ${THRESHOLD}% line coverage threshold."
  else
    for f in "${BELOW_FILES[@]}"; do
      log_warn "  $f"
    done
    echo ""
    log_warn "${#BELOW_FILES[@]} file(s) below threshold."
  fi

fi

echo ""
echo "=== SUGGESTIONS ==="
echo ""
echo "1. Focus on branch coverage first — uncovered branches = untested conditions."
echo "2. Exclude generated/config files: add to coverage.exclude in vitest.config.ts"
echo "3. For files with 0% coverage — are they dead code? Delete them or add tests."
echo "4. For near-threshold files — add tests for error paths (null inputs, exceptions)."
echo "5. Consider Stryker mutation testing: npx stryker run (for domain logic files)"
echo ""
echo "Docs: references/coverage-strategy.md"
echo ""
